// Suggestions for the School field. Not exhaustive: people can always type a school that isn't listed.
const LIST = [
  // Mississippi and the South
  "Mississippi State University", "University of Mississippi", "University of Southern Mississippi", "Jackson State University",
  "Delta State University", "Mississippi College", "Millsaps College", "Alcorn State University", "Mississippi Valley State University",
  "Belhaven University", "William Carey University", "Mississippi University for Women",
  // SEC
  "University of Alabama", "Auburn University", "University of Arkansas", "University of Florida", "University of Georgia",
  "University of Kentucky", "Louisiana State University", "University of Missouri", "University of Oklahoma",
  "University of South Carolina", "University of Tennessee", "Texas A&M University", "University of Texas at Austin",
  "Vanderbilt University",
  // Big Ten
  "University of Illinois Urbana-Champaign", "Indiana University Bloomington", "University of Iowa", "University of Maryland",
  "University of Michigan", "Michigan State University", "University of Minnesota", "University of Nebraska-Lincoln",
  "Northwestern University", "Ohio State University", "Penn State University", "Purdue University", "Rutgers University",
  "University of Wisconsin-Madison", "UCLA", "University of Southern California", "University of Oregon", "University of Washington",
  // ACC
  "Boston College", "Clemson University", "Duke University", "Florida State University", "Georgia Tech", "University of Louisville",
  "University of Miami", "University of North Carolina at Chapel Hill", "NC State University", "University of Notre Dame",
  "University of Pittsburgh", "Syracuse University", "University of Virginia", "Virginia Tech", "Wake Forest University",
  "Stanford University", "University of California, Berkeley", "Southern Methodist University",
  // Big 12
  "University of Arizona", "Arizona State University", "Baylor University", "Brigham Young University", "University of Central Florida",
  "University of Cincinnati", "University of Colorado Boulder", "University of Houston", "Iowa State University", "University of Kansas",
  "Kansas State University", "Oklahoma State University", "Texas Christian University", "Texas Tech University", "University of Utah",
  "West Virginia University",
  // Ivy League and top private
  "Brown University", "Columbia University", "Cornell University", "Dartmouth College", "Harvard University", "Princeton University",
  "University of Pennsylvania", "Yale University", "Massachusetts Institute of Technology", "University of Chicago",
  "Johns Hopkins University", "Georgetown University", "Rice University", "Emory University", "Washington University in St. Louis",
  "Carnegie Mellon University", "New York University", "Boston University", "Tufts University", "Tulane University",
  "Northeastern University", "Fordham University", "Villanova University", "Lehigh University", "Bucknell University",
  "Babson College", "Bentley University", "Case Western Reserve University",
  "University of Rochester", "Brandeis University", "Wesleyan University", "Williams College", "Amherst College",
  "Middlebury College", "Bowdoin College", "Colgate University", "Hamilton College", "Davidson College", "Washington and Lee University",
  "University of Richmond", "College of William & Mary", "Furman University", "Elon University", "Santa Clara University",
  "Pepperdine University", "Loyola Marymount University", "University of San Diego", "Gonzaga University", "Creighton University",
  "Marquette University", "Saint Louis University", "Loyola University Chicago", "DePaul University", "Xavier University",
  "University of Dayton", "Butler University", "Drake University", "Belmont University", "Lipscomb University", "Samford University",
  "Trinity University", "University of Tulsa", "Wofford College",
  "Providence College", "Fairfield University", "Quinnipiac University", "Seton Hall University", "Stevens Institute of Technology",
  "Rensselaer Polytechnic Institute", "Worcester Polytechnic Institute", "Baruch College",
  "Pace University", "St. John's University", "Hofstra University", "Manhattan College", "Saint Joseph's University", "Drexel University", "Temple University", "La Salle University", "Loyola University Maryland",
  "Towson University", "George Washington University", "American University", "Catholic University of America", "Howard University",
  // Large public universities
  "University of California, Davis", "University of California, Irvine", "University of California, San Diego",
  "University of California, Santa Barbara", "University of California, Santa Cruz", "University of California, Riverside",
  "San Diego State University", "San Jose State University", "California State University, Fullerton",
  "California State University, Long Beach", "California Polytechnic State University", "University of Nevada, Las Vegas",
  "University of Nevada, Reno", "University of New Mexico", "New Mexico State University", "Colorado State University",
  "University of Denver", "Boise State University", "Montana State University", "University of Montana", "Utah State University",
  "Oregon State University", "Portland State University", "Washington State University", "University of Idaho",
  "University of Hawaii at Manoa", "University of Alaska Anchorage", "University of Texas at Dallas", "University of Texas at Arlington",
  "University of Texas at San Antonio", "University of North Texas", "Texas State University", "Sam Houston State University",
  "Stephen F. Austin State University", "Texas A&M University-Corpus Christi", "University of Texas Rio Grande Valley",
  "University of Arkansas at Little Rock", "Arkansas State University", "University of Central Arkansas", "University of Memphis",
  "Middle Tennessee State University", "Tennessee Technological University", "East Tennessee State University",
  "University of Tennessee at Chattanooga", "University of Alabama at Birmingham", "University of South Alabama",
  "Troy University", "Jacksonville State University", "University of North Alabama", "Louisiana Tech University",
  "University of Louisiana at Lafayette", "University of New Orleans", "Southeastern Louisiana University", "Loyola University New Orleans",
  "Georgia State University", "Kennesaw State University", "Georgia Southern University", "Mercer University",
  "Florida International University", "Florida Atlantic University", "University of South Florida", "University of North Florida",
  "Florida Gulf Coast University", "Stetson University", "Rollins College", "University of Tampa", "Florida A&M University",
  "College of Charleston", "Coastal Carolina University", "Winthrop University", "Appalachian State University",
  "East Carolina University", "University of North Carolina at Charlotte", "University of North Carolina Wilmington",
  "University of North Carolina at Greensboro", "James Madison University", "George Mason University", "Old Dominion University",
  "Virginia Commonwealth University", "Radford University", "Marshall University", "University of Delaware",
  "University of Maryland, Baltimore County", "Penn State Behrend", "University of Connecticut", "University of Massachusetts Amherst",
  "University of Massachusetts Boston", "University of Rhode Island", "University of Vermont", "University of New Hampshire",
  "University of Maine", "Stony Brook University", "University at Buffalo", "Binghamton University", "University at Albany",
  "Rochester Institute of Technology", "Ohio University", "Miami University", "Kent State University", "Bowling Green State University",
  "University of Toledo", "University of Akron", "Wright State University", "Cleveland State University", "Ball State University",
  "Indiana State University", "IUPUI", "Western Michigan University", "Central Michigan University", "Eastern Michigan University",
  "Wayne State University", "Grand Valley State University", "Oakland University", "Northern Illinois University", "Illinois State University",
  "Southern Illinois University", "University of Illinois Chicago", "Bradley University",
  "University of Wisconsin-Milwaukee", "University of Wisconsin-Eau Claire", "University of Wisconsin-Whitewater",
  "University of Minnesota Duluth", "St. Cloud State University", "University of St. Thomas", "University of North Dakota",
  "North Dakota State University", "University of South Dakota", "South Dakota State University", "University of Northern Iowa",
  "University of Nebraska Omaha", "Wichita State University", "Missouri State University", "University of Missouri-Kansas City",
  "University of Missouri-St. Louis", "Truman State University", "University of Central Missouri", "Western Kentucky University",
  "Eastern Kentucky University", "Murray State University", "Northern Kentucky University", "Bellarmine University",
  // HBCUs
  "Spelman College", "Morehouse College", "Hampton University", "North Carolina A&T State University", "Tuskegee University",
  "Southern University and A&M College", "Grambling State University", "Texas Southern University", "Prairie View A&M University",
  "Clark Atlanta University", "Xavier University of Louisiana", "Morgan State University", "Bowie State University",
  "Delaware State University", "Tennessee State University", "Alabama State University", "Alabama A&M University",
  "Norfolk State University", "Virginia State University", "North Carolina Central University", "Fisk University", "Dillard University",
  // Service academies
  "United States Military Academy", "United States Naval Academy", "United States Air Force Academy",
];

export const UNIVERSITIES = [...new Set(LIST)].sort((a, b) => a.localeCompare(b));
