import { CONTACT_EMAIL, LegalPage } from "@/components/LegalPage";

export const metadata = { title: "Terms of Service | Orbit" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p>By creating an account or using Orbit, you agree to these terms.</p>

      <h2>The service</h2>
      <p>
        Orbit is a personal relationship manager that organizes information you provide and generates AI-assisted
        summaries, reminders and message drafts. Orbit is currently in beta: features may change, and the service may
        be interrupted.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must be at least 16 and provide accurate information.</li>
        <li>You&apos;re responsible for keeping your login secure and for activity under your account.</li>
      </ul>

      <h2>Your content</h2>
      <p>
        You keep ownership of everything you upload or create. You give us permission to store and process it only to
        operate Orbit for you, as described in the Privacy Policy. You confirm you have the right to upload the data you
        provide (for example, your own LinkedIn export).
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use Orbit to manage genuine professional relationships, not to send spam, harass anyone, or scrape or resell data.</li>
        <li>Follow the terms of the services you connect, including LinkedIn and Google.</li>
        <li>Don&apos;t try to access other users&apos; data, overload the service, or bypass usage limits.</li>
      </ul>

      <h2>AI features</h2>
      <p>
        Summaries, suggestions and drafts are generated by AI and can be incomplete or wrong. Review everything before
        relying on it or sending it. You are responsible for the messages you send.
      </p>

      <h2>Usage limits</h2>
      <p>To keep Orbit free during beta, AI features have daily limits that we may adjust.</p>

      <h2>Ending your account</h2>
      <p>
        You can delete your account at any time from the Me tab. We may suspend accounts that violate these terms.
      </p>

      <h2>Disclaimers and liability</h2>
      <p>
        Orbit is provided &quot;as is&quot; without warranties of any kind. To the extent permitted by law, we are not liable for
        indirect or consequential damages, or for any recruiting or employment outcome.
      </p>

      <h2>Changes and contact</h2>
      <p>
        We may update these terms and will notify you of material changes. Questions:{" "}
        <a className="text-accent" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
